In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [12]:
df = pd.read_csv("C://Users/Jatin/Desktop/Lp3prac/ML/emails.csv")
df.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [13]:
df.isnull().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [14]:
df.drop('Email No.',axis=1,inplace=True)

In [15]:
x=df.drop(['Prediction'],axis=1)
y=df['Prediction']

In [16]:
from sklearn.preprocessing import scale
x=scale(x)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [17]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
print("Prediction ",y_pred)

Prediction  [1 0 1 ... 1 1 0]


C:\Users\Jatin\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [18]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("KNN accuracy ",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

KNN accuracy  0.7667525773195877
[[770 347]
 [ 15 420]]


In [20]:
from sklearn.svm import SVC
#cost C=1
model=SVC(C=1)
#fit
model.fit(x_train,y_train)
#predict
pred=model.predict(x_test)
print(pred)

[0 0 1 ... 1 1 0]


In [21]:
print("SVM Accuracy ",accuracy_score(y_test,pred))
print(confusion_matrix(y_test,pred))

SVM Accuracy  0.9381443298969072
[[1110    7]
 [  89  346]]
